package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ajustes_ventana extends Panel {
	protected VerticalLayout main;
	protected Image logo;
	protected Label nombreUsuario;
	protected VerticalLayout listaNotificaciones;
	protected HorizontalLayout notificacion1;
	protected Label tituloNotificacion;
	protected Button eliminarNotificacion;
	protected Button aceptarNotificacion;
	protected Button visualizarNotificacion;
	protected HorizontalLayout notificacion2;
	protected Label tituloNotificacion1;
	protected Button eliminarNotificacion1;
	protected Button aceptarNotificacion1;
	protected Button visualizarNotificacion1;
	protected HorizontalLayout notificacion3;
	protected Label tituloNotificacion2;
	protected Button eliminarNotificacion2;
	protected Button aceptarNotificacion2;
	protected Button visualizarNotificacion2;
	protected Button notificacionAtras;
	protected Button notificacionAdelante;
	protected Button inicio;
	protected Button notificaciones;
	protected Button ajustes;
	protected Button cerrarSesion;
	protected Button registrarse;
	protected Button iniciarSesion;
	protected Button perfil;
	protected Button usuariosB;
	protected Button amigos;
	protected Button usuariosReportados;
	protected Button usuariosBaneados;
	protected VerticalLayout main2;
	protected VerticalLayout datosPerfil;
	protected HorizontalLayout informacionUsuario;
	protected Image fotoUsuario;
	protected Label nombreCompleto;
	protected Label email;
	protected Label descripcion;
	protected CheckBox notificacionesPorCorreo;
	protected Button modificarContrasena;
	protected Button modificarPerfil;
	protected VerticalLayout listaUsuarios;
	protected HorizontalLayout movimientoPaginas;
	protected Button pagAntUsu;
	protected Button pagAdeUsu;

	public Ajustes_ventana() {
		Design.read(this);
	}
}
