package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ajustes_ventana extends Panel {
	protected VerticalLayout main;
	protected Image logo;
	protected Label nombreUsuario;
	protected HorizontalLayout tipoUsuario;
	protected VerticalLayout tipoAjuste;
	protected VerticalLayout datos;
	protected HorizontalLayout movimientoPaginas;
	protected Button pagAntUsu;
	protected Button pagAdeUsu;

	public Ajustes_ventana() {
		Design.read(this);
	}
}
