package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g
 * class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Comun_usuarios_ventana extends Panel {
	protected Image logo;
	protected Label nombreUsuario;
	protected HorizontalLayout tipoUsuario;
	protected VerticalLayout cuadroPrincipal;
	protected Label seccionesLabel;
	protected VerticalLayout listaDeSecciones;
	protected Button pagAtraSecciones;
	protected Button pagAdeSecciones;
	protected VerticalLayout temasRecientes;
	protected Label temasLabel;
	protected HorizontalLayout tema1;
	protected Label nombreTema;
	protected Label usuarioCreadorTema;
	protected Button borrarTema;
	protected Label ultimoMensaje;
	protected Label diaEnviado;
	protected Label numeroComentariosTema;
	protected Label numeroLikesTema;
	protected HorizontalLayout tema2;
	protected Label nombreTema1;
	protected Label usuarioCreadorTema1;
	protected Button borrarTema1;
	protected Label ultimoMensaje1;
	protected Label diaEnviado1;
	protected Label numeroComentariosTema1;
	protected Label numeroLikesTema1;
	protected HorizontalLayout tema3;
	protected Label nombreTema2;
	protected Label usuarioCreadorTema2;
	protected Button borrarTema2;
	protected Label ultimoMensaje2;
	protected Label diaEnviado2;
	protected Label numeroComentariosTema2;
	protected Label numeroLikesTema2;
	protected VerticalLayout mensajesRecientes;
	protected HorizontalLayout mensaje1;
	protected Label contenidoInicial;
	protected Label usuarioCreadorMensaje;
	protected Button borrarMensaje;
	protected Label temaPerteneciente;
	protected Label horaYDiaMensaje;
	protected Label numLikesMensaje;
	protected HorizontalLayout mensaje2;
	protected Label contenidoInicial1;
	protected Label usuarioCreadorMensaje1;
	protected Button borrarMensaje1;
	protected Label temaPerteneciente1;
	protected Label horaYDiaMensaje1;
	protected Label numLikesMensaje1;
	protected HorizontalLayout mensaje3;
	protected Label contenidoInicial2;
	protected Label usuarioCreadorMensaje2;
	protected Button borrarMensaje2;
	protected Label temaPerteneciente2;
	protected Label horaYDiaMensaje2;
	protected Label numLikesMensaje2;
	protected VerticalLayout cuadroSeccion;
	protected TextField nombreSeccion;
	protected Button crearSeccion;

	public Comun_usuarios_ventana() {
		Design.read(this);
	}
}
