package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class LabelMensaje_ventana extends HorizontalLayout {
	protected Label contenidoInicial;
	protected Label usuarioCreadorMensaje;
	protected Button borrarMensaje;
	protected Label temaPerteneciente;
	protected Label horaYDiaMensaje;
	protected Label numLikesMensaje;

	public LabelMensaje_ventana() {
		Design.read(this);
	}
}
