package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Mensajes_propios_ventana extends HorizontalLayout {
	protected Image fotoMensaje;
	protected Label usuarioMensaje;
	protected Label fechaMensaje;
	protected Label contenidoMensaje;
	protected Button borrarMensaje;
	protected Button citarMensaje;
	protected Label numLikesMensaje;
	protected Button likeMensaje;

	public Mensajes_propios_ventana() {
		Design.read(this);
	}
}
