package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Mensajes_ventana extends Panel {
	protected VerticalLayout background;
	protected Image logo;
	protected Label nombreUsuario;
	protected HorizontalLayout tipoUsuario;
	protected HorizontalLayout foroLink;
	protected HorizontalLayout seccionLink;
	protected Label seccion;
	protected Label tema;
	protected Image fotoTema;
	protected Label usuarioTema;
	protected Label tituloTema;
	protected Label fechaTema;
	protected Label contenidoTema;
	protected Button ocultarTema;
	protected Button mostrarTema;
	protected Button borrarTema;
	protected Label numComentariosTema;
	protected Label numLikesTema;
	protected Button likeTema;
	protected VerticalLayout listaMensajes;
	protected Button pagAtrMensaje;
	protected Button pagAdeMensaje;

	public Mensajes_ventana() {
		Design.read(this);
	}
}
