package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Registrarse_ventana extends Panel {
	protected NativeButton salir;
	protected Label titulo;
	protected TextField nombreUsuario;
	protected PasswordField contrasena;
	protected PasswordField contrasena2;
	protected TextField email;
	protected TextField nombreCompleto;
	protected TextField descripcion;
	protected NativeButton adjuntar;
	protected NativeButton registrarse;

	public Registrarse_ventana() {
		Design.read(this);
	}
}
