package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Seccion_ventana extends Panel {
	protected Image logo;
	protected Label nombreUsuario;
	protected Button notificaciones;
	protected Button ajustes;
	protected Button cerrarSesion;
	protected HorizontalLayout seccionLink;
	protected Label seccion;
	protected HorizontalLayout tema1;
	protected Label nombreTema;
	protected Label usuarioCreadorTema;
	protected Button borrarTema;
	protected Label ultimoMensaje;
	protected Label diaEnviado;
	protected Label numeroComentariosTema;
	protected Label numeroLikesTema;
	protected Image meGusta;
	protected HorizontalLayout tema2;
	protected Label nombreTema1;
	protected Label usuarioCreadorTema1;
	protected Button borrarTema1;
	protected Label ultimoMensaje1;
	protected Label diaEnviado1;
	protected Label numeroComentariosTema1;
	protected Label numeroLikesTema1;
	protected Image meGusta1;
	protected HorizontalLayout tema3;
	protected Label nombreTema2;
	protected Label usuarioCreadorTema2;
	protected Button borrarTema2;
	protected Label ultimoMensaje2;
	protected Label diaEnviado2;
	protected Label numeroComentariosTema2;
	protected Label numeroLikesTema2;
	protected Image meGusta2;
	protected HorizontalLayout tema4;
	protected Label nombreTema3;
	protected Label usuarioCreadorTema3;
	protected Button borrarTema3;
	protected Label ultimoMensaje3;
	protected Label diaEnviado3;
	protected Label numeroComentariosTema3;
	protected Label numeroLikesTema3;
	protected Image meGusta3;
	protected HorizontalLayout tema5;
	protected Label nombreTema4;
	protected Label usuarioCreadorTema4;
	protected Button borrarTema4;
	protected Label ultimoMensaje4;
	protected Label diaEnviado4;
	protected Label numeroComentariosTema4;
	protected Label numeroLikesTema4;
	protected Image meGusta4;
	protected Button pagAtrTema;
	protected Button pagAdeTema;
	protected TextField tituloTema;
	protected TextArea contenidoTema;
	protected Button crearTema;

	public Seccion_ventana() {
		Design.read(this);
	}
}
