package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Tema_ventana extends Panel {
	protected Image logo;
	protected Label nombreUsuario;
	protected Button notificaciones;
	protected Button ajustes;
	protected Button cerrarSesion;
	protected Button registrarse;
	protected Button iniciarSesion;
	protected HorizontalLayout foroLink;
	protected HorizontalLayout seccionLink;
	protected Label seccion;
	protected Label tema;
	protected Image fotoTema;
	protected Label usuarioTema;
	protected Label tituloTema;
	protected Label fechaTema;
	protected Label contenidoTema;
	protected Button borrarTema;
	protected Label numComentariosTema;
	protected Label numLikesTema;
	protected Button likeTema;
	protected HorizontalLayout mensaje;
	protected Image fotoMensaje;
	protected Label usuarioMensaje;
	protected Label fechaMensaje;
	protected Label contenidoMensaje;
	protected Button borrarMensaje;
	protected Button citarMensaje;
	protected Label numLikesMensaje;
	protected Button likeMensaje;
	protected HorizontalLayout mensaje1;
	protected Image fotoMensaje1;
	protected Label usuarioMensaje1;
	protected Label fechaMensaje1;
	protected Label contenidoMensaje1;
	protected Button borrarMensaje1;
	protected Button citarMensaje1;
	protected Label numLikesMensaje1;
	protected Button likeMensaje1;
	protected HorizontalLayout mensaje2;
	protected Image fotoMensaje2;
	protected Label usuarioMensaje2;
	protected Label fechaMensaje2;
	protected Label contenidoMensaje2;
	protected Button borrarMensaje2;
	protected Button citarMensaje2;
	protected Label numLikesMensaje2;
	protected Button likeMensaje2;
	protected HorizontalLayout mensaje3;
	protected Image fotoMensaje3;
	protected Label usuarioMensaje3;
	protected Label fechaMensaje3;
	protected Label contenidoMensaje3;
	protected Button borrarMensaje3;
	protected Button citarMensaje3;
	protected Label numLikesMensaje3;
	protected Button likeMensaje3;
	protected HorizontalLayout mensaje4;
	protected Image fotoMensaje4;
	protected Label usuarioMensaje4;
	protected Label fechaMensaje4;
	protected Label contenidoMensaje4;
	protected Button borrarMensaje4;
	protected Button citarMensaje4;
	protected Label numLikesMensaje4;
	protected Button likeMensaje4;
	protected Button pagAtrMensaje;
	protected Button pagAdeMensaje;
	protected VerticalLayout cuadroMensaje;
	protected TextArea contenidoComentario;
	protected Button enviarComentario;

	public Tema_ventana() {
		Design.read(this);
	}
}
