package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Temas_ventana extends Panel {
	protected VerticalLayout background;
	protected Image logo;
	protected Label nombreUsuario;
	protected VerticalLayout listaNotificaciones;
	protected HorizontalLayout notificacion1;
	protected Label tituloNotificacion;
	protected Button eliminarNotificacion;
	protected Button aceptarNotificacion;
	protected Button visualizarNotificacion;
	protected HorizontalLayout notificacion2;
	protected Label tituloNotificacion1;
	protected Button eliminarNotificacion1;
	protected Button aceptarNotificacion1;
	protected Button visualizarNotificacion1;
	protected HorizontalLayout notificacion3;
	protected Label tituloNotificacion2;
	protected Button eliminarNotificacion2;
	protected Button aceptarNotificacion2;
	protected Button visualizarNotificacion2;
	protected Button notificacionAtras;
	protected Button notificacionAdelante;
	protected HorizontalLayout tipoUsuario;
	protected HorizontalLayout foroLink;
	protected HorizontalLayout seccionLink1;
	protected Label seccion1;
	protected HorizontalLayout seccionLink;
	protected Label seccion;
	protected VerticalLayout listaTemas;
	protected Button pagAtrTema;
	protected Button pagAdeTema;

	public Temas_ventana() {
		Design.read(this);
	}
}
