package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Usuarios_Para_Revision_ventana extends Panel {
	protected VerticalLayout main;
	protected VerticalLayout listaUsuarios;
	protected Label nombreLista;
	protected HorizontalLayout filaUsuario;
	protected Label correoUsuario;
	protected Button banear;
	protected Button quitarReporte;
	protected HorizontalLayout filaUsuario1;
	protected Label correoUsuario1;
	protected Button banear1;
	protected Button quitarReporte1;
	protected HorizontalLayout filaUsuario2;
	protected Label correoUsuario2;
	protected Button banear2;
	protected Button quitarReporte2;
	protected HorizontalLayout filaUsuario3;
	protected Label correoUsuario3;
	protected Button banear3;
	protected Button quitarReporte3;
	protected HorizontalLayout filaUsuario4;
	protected Label correoUsuario4;
	protected Button banear4;
	protected Button quitarReporte4;
	protected HorizontalLayout filaUsuario5;
	protected Label correoUsuario5;
	protected Button banear5;
	protected Button quitarReporte5;
	protected HorizontalLayout filaUsuario6;
	protected Label correoUsuario6;
	protected Button banear6;
	protected Button quitarReporte9;
	protected HorizontalLayout filaUsuario7;
	protected Label correoUsuario7;
	protected Button banear7;
	protected Button quitarReporte6;
	protected HorizontalLayout filaUsuario8;
	protected Label correoUsuario8;
	protected Button banear8;
	protected Button quitarReporte7;
	protected HorizontalLayout filaUsuario9;
	protected Label correoUsuario9;
	protected Button banear9;
	protected Button quitarReporte8;
	protected VerticalLayout cargaUsuario;
	protected Button cerrarVista;
	protected Button banearUs;
	protected Button desbanear;
	protected Button reportar;
	protected Button quitarReporte10;
	protected Button hacerModerador;
	protected Button quitarModerador;

	public Usuarios_Para_Revision_ventana() {
		Design.read(this);
	}
}
