package com.mds.foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Usuario_ventana extends VerticalLayout {
	protected VerticalLayout componentes;
	protected HorizontalLayout datosPerfil;
	protected Image fotoUsuario;
	protected Label nombreCompleto;
	protected Label email;
	protected Label descripcion;
	protected Button desbanear;
	protected Button banear;
	protected Button quitarReporte;
	protected Button reportar;
	protected Button hacerModerador;
	protected Button quitarModerador;
	protected Button enviarSolicitud;
	protected Button eliminarAmigo;
	protected Button cerrarVista;
	protected HorizontalLayout configuracionUsuario;
	protected CheckBox notificacionesPorCorreo;
	protected Button modificarContrasena;
	protected Button modificarPerfil;

	public Usuario_ventana() {
		Design.read(this);
	}
}
